# Generated by Django 5.0.6 on 2024-05-23 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTeam',
            fields=[
                ('coremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coreApp.coremodel')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='myTeam/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            bases=('coreApp.coremodel',),
        ),
        migrations.CreateModel(
            name='RegisterTeam',
            fields=[
                ('coremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coreApp.coremodel')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('direction', models.CharField(choices=[("Onlayn do'kon", "Onlayn do'kon"), ('Consulting', 'Consulting'), ("O'quv markaz", "O'quv markaz"), ('Onlayn sotuv (kurs vhk)', 'Onlayn sotuv (kurs vhk)'), ('Universitet maktab', 'Universitet maktab'), ('Mebel (sotish va ishlab chiqarish)', 'Mebel (sotish va ishlab chiqarish)'), ('Ishlab chiqarish', 'Ishlab chiqarish'), ("Xizmat ko'rsatish", "Xizmat ko'rsatish"), ('Tur firma', 'Tur firma'), ('Sotuv oflayn', 'Sotuv oflayn')], default="Onlayn do'kon", max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            bases=('coreApp.coremodel',),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('coremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coreApp.coremodel')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='services/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            bases=('coreApp.coremodel',),
        ),
        migrations.CreateModel(
            name='UsAbout',
            fields=[
                ('coremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coreApp.coremodel')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='usAbout/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            bases=('coreApp.coremodel',),
        ),
    ]
