# Generated by Django 5.0.6 on 2024-05-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myteam',
            name='image',
            field=models.ImageField(upload_to='myTeam'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='services'),
        ),
        migrations.AlterField(
            model_name='usabout',
            name='image',
            field=models.ImageField(upload_to='usAbout'),
        ),
    ]
