# Generated by Django 5.0.6 on 2024-05-24 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_myteam_image_alter_services_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerteam',
            name='direction',
        ),
    ]
