# Generated by Django 5.0.6 on 2024-05-24 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0001_initial'),
        ('mainApp', '0003_remove_registerteam_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('coremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coreApp.coremodel')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='partners')),
            ],
            bases=('coreApp.coremodel',),
        ),
    ]
